extends: default

ignore: |
  frontend/node_modules/
  e2e/node_modules/
  frontend/pnpm-lock.yaml
  e2e/pnpm-lock.yaml
  backend/target/

rules:
  document-start: disable  # GitHub Actions workflows don't use ---
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false  # prevents false positive on "on:" in GitHub Actions workflows
  line-length:
    max: 120
    allow-non-breakable-words: true
  comments:
    require-starting-space: true
    min-spaces-from-content: 1  # SHA pin comments use single space (e.g. "# v4.2.2")
